# Generated by Django 3.2.6 on 2021-08-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=100)),
                ('rate', models.FloatField()),
                ('description', models.CharField(max_length=254)),
            ],
        ),
    ]
